// sprites.js — ForkArcade sprite atlas
// Source: _spritesheet.png (160x30, 16 cols x 3 rows, 10x10 per frame)
// Generated by _convert_sprites.py

FA.assets.spritesheet = new Image();
FA.assets.spritesheet.src = '_spritesheet.png';
FA.assets.sheetCols = 16;

FA.assets.spriteDefs = {
  "objects": {
    "bed": {w:10, h:10, origin:[0, 0], frames:[0]},
    "terminal": {w:10, h:10, origin:[0, 0], frames:[1]},
    "notice_board": {w:10, h:10, origin:[0, 0], frames:[2]},
    "system_entrance": {w:10, h:10, origin:[0, 0], frames:[3]},
    "cafe_table": {w:10, h:10, origin:[0, 0], frames:[4]},
    "dungeon_stairs": {w:10, h:10, origin:[0, 0], frames:[5]},
    "dungeon_terminal": {w:10, h:10, origin:[0, 0], frames:[6, 7]}
  },
  "tiles": {
    "floor": {w:10, h:10, origin:[0, 0], frames:[8, 9], tiling:'checker'},
    "wall": {w:10, h:10, origin:[0, 0], frames:[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], tiling:'autotile'},
    "indoor": {w:10, h:10, origin:[0, 0], frames:[26, 27], tiling:'checker'},
    "garden": {w:10, h:10, origin:[0, 0], frames:[28]},
    "sidewalk": {w:10, h:10, origin:[0, 0], frames:[29]},
    "dungeon_floor": {w:10, h:10, origin:[0, 0], frames:[30, 31], tiling:'checker'},
    "dungeon_wall": {w:10, h:10, origin:[0, 0], frames:[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47], tiling:'autotile'}
  }
};
