// sprites.js — ForkArcade sprite atlas
// Source: _spritesheet.png (160x90, 16 cols x 9 rows, 10x10 per frame)
// Generated by _convert_to_png.py

var SPRITESHEET = new Image();
SPRITESHEET.src = '_spritesheet.png';
var SPRITE_SHEET_COLS = 16;

var SPRITE_DEFS = {
  "objects": {
    "bed": {w:10, h:10, origin:[0,0], frames:[0]},
    "terminal": {w:10, h:10, origin:[0,0], frames:[1]},
    "notice_board": {w:10, h:10, origin:[0,0], frames:[2]},
    "system_entrance": {w:10, h:10, origin:[0,0], frames:[3]},
    "cafe_table": {w:10, h:10, origin:[0,0], frames:[4]}
  },
  "tiles": {
    "floor": {w:10, h:10, origin:[0,0], frames:[5,6]},
    "wall": {w:10, h:10, origin:[0,0], frames:[7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]},
    "indoor": {w:10, h:10, origin:[0,0], frames:[23,24]},
    "garden": {w:10, h:10, origin:[0,0], frames:[25]},
    "sidewalk": {w:10, h:10, origin:[0,0], frames:[26]},
    "dungeon_d0_floor": {w:10, h:10, origin:[0,0], frames:[27,28]},
    "dungeon_d0_wall": {w:10, h:10, origin:[0,0], frames:[29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44]},
    "dungeon_d1_floor": {w:10, h:10, origin:[0,0], frames:[45,46]},
    "dungeon_d1_wall": {w:10, h:10, origin:[0,0], frames:[47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62]},
    "dungeon_d2_floor": {w:10, h:10, origin:[0,0], frames:[63,64]},
    "dungeon_d2_wall": {w:10, h:10, origin:[0,0], frames:[65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80]},
    "dungeon_d3_floor": {w:10, h:10, origin:[0,0], frames:[81,82]},
    "dungeon_d3_wall": {w:10, h:10, origin:[0,0], frames:[83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98]},
    "dungeon_d4_floor": {w:10, h:10, origin:[0,0], frames:[99,100]},
    "dungeon_d4_wall": {w:10, h:10, origin:[0,0], frames:[101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116]},
    "dungeon_d5_floor": {w:10, h:10, origin:[0,0], frames:[117,118]},
    "dungeon_d5_wall": {w:10, h:10, origin:[0,0], frames:[119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134]},
    "dungeon_stairs": {w:10, h:10, origin:[0,0], frames:[135]},
    "dungeon_terminal": {w:10, h:10, origin:[0,0], frames:[136]},
    "dungeon_terminal_used": {w:10, h:10, origin:[0,0], frames:[137]}
  }
};
